/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotel_dawud;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.text.ParseException;
import javax.swing.JTable;
import java.io.File;
import java.sql.DriverManager;
import java.util.HashMap;

/**
 *
 * @author CHACA
 */
public class level extends javax.swing.JFrame {
          public Connection kon;
    public Statement stt;
    public ResultSet rs;

    /**
     * Creates new form level
     */
    public level() {
        initComponents();
         normal();
        jTable1.setModel(tblModel);
        Tabel(jTable1,new int[]{55,110,210,110,110,110});
        setDefaultTable();
        
    }
        
    public void normal(){
    id_level.setText("");
    nama_level.setText("");
    id_level.setEnabled(false);
    nama_level.setEnabled(false);
    tambah.setEnabled(true);
    simpan.setEnabled(false);
    ubah.setEnabled(false);
    hapus.setEnabled(false);
    batal.setEnabled(false);
    keluar.setEnabled(false);
    
    }
    
    String data[]=new String[6];
    
    public void setDefaultTable(){
    
    String hubung = "jdbc:mysql://localhost:3306/db_hotel";
    try{
    Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stmt = kon.createStatement();
            String SQL = "Select*from level";
              ResultSet res = stmt.executeQuery(SQL);
              while(res.next()){
              data[0]=res.getString(1);
              data[1]=res.getString(2);
              tblModel.addRow(data);
              }
              res.close();
              stt.close();
              kon.close();
    }
    catch(Exception exc){
        System.err.println(exc.getMessage());
    }
    }
    
    
         private final javax.swing.table.DefaultTableModel tblModel = getDefaultTabelModel();
    
    private void Tabel(javax.swing.JTable tb, int lebar[]){
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int kolom=tb.getColumnCount();
        for(int i=0;i<kolom;i++){
            javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);
            tb.setRowHeight(17);
        }
    }
    
    
    
    
    private javax.swing.table.DefaultTableModel getDefaultTabelModel(){
        return new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"id_level,nama_level"}){
                boolean[]canEdit=new boolean[]{
                    false,false,false,false};
        public boolean isCallEditable(int rowIndex,int coloumnIndex){
            return canEdit[coloumnIndex];
        }
        };
        }
    
    
     private void autokode(){
        String hubung = "jdbc:mysql://localhost:3306/db_hotel";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stmt = kon.createStatement();
            String SQL = "SELECT MAX(right(id_level,2)) AS no FROM level";
            ResultSet rs = stmt.executeQuery(SQL);
                while(rs.next())
                {
                    if(rs.first()==false)
                    {
                        id_level.setText("0");
                    }
                    else
                    {
                        rs.last();
                        int auto_nis=rs.getInt(1)+1;
                        String no = String.valueOf(auto_nis);
                        int noLong = no.length();
                        for(int a=0;a<3-noLong;a++)
                    {
                        no = "0" + no;
                    }
                    id_level.setText("0"+no);
                        } 
                }
                rs.close();
                stmt.close();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "ERROR:\n" + e.toString(),
                    "Kesalahan",JOptionPane.WARNING_MESSAGE);
        }
    }   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_level = new javax.swing.JTextField();
        nama_level = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tcari2 = new javax.swing.JTextField();
        ccari4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel1.setText("Id Level");

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel2.setText("Nama Level");

        id_level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_levelActionPerformed(evt);
            }
        });

        tambah.setText("tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        simpan.setText("simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        batal.setText("batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        ubah.setText("ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        hapus.setText("hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        keluar.setText("keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel3.setText("Masukan Nama level");

        ccari4.setText("cari");
        ccari4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccari4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tcari2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ccari4)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcari2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccari4))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nama_level, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_level, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(tambah)
                                .addGap(18, 18, 18)
                                .addComponent(simpan)
                                .addGap(18, 18, 18)
                                .addComponent(batal)
                                .addGap(18, 18, 18)
                                .addComponent(ubah)
                                .addGap(18, 18, 18)
                                .addComponent(hapus)
                                .addGap(18, 18, 18)
                                .addComponent(keluar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(simpan)
                    .addComponent(batal)
                    .addComponent(ubah)
                    .addComponent(hapus)
                    .addComponent(keluar))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        normal();
        id_level.setEnabled(false);
        id_level.setText("");
        nama_level.setEnabled(false);
        nama_level.setText("");
        
    }//GEN-LAST:event_batalActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        Object[]options={"YA","TIDAK"};
        int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Menghapus Data?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        if(konfirmasi==JOptionPane.YES_OPTION){
            try{
                koneksi();
                Statement stt=kon.createStatement();
                String SQL="delete from level where id_level='"+id_level.getText()+"'";
                stt.executeUpdate(SQL);
                tblModel.removeRow(row);
                normal();
                stt.close();
                kon.close();
            }catch(Exception exc){
                System.err.println(exc.getMessage());
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        autokode();
        id_level.setEnabled(false);
    nama_level.setEnabled(true);
    nama_level.requestFocus(true);
    tambah.setEnabled(false);
    simpan.setEnabled(true);
    ubah.setEnabled(false);
    hapus.setEnabled(false);
    batal.setEnabled(true);
    keluar.setEnabled(true);
    }//GEN-LAST:event_tambahActionPerformed

    private void ccari4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccari4ActionPerformed
        // TODO add your handling code here:
            koneksi();
         try{
         String hubung = "jdbc:mysql://localhost:3306/db_hotel";
         Class.forName("com.mysql.jdbc.Driver").newInstance();
         Connection kon =DriverManager.getConnection(hubung, "root","");
         String cari = tcari2.getText();
         String sql = "select * from level where nama_level like '"+cari+"'";
         Statement stt = kon.createStatement();
         ResultSet res=stt.executeQuery(sql);
         if(res.next()){
         id_level.setText(res.getString(1));
         nama_level.setText(res.getString(2));
        
         
         id_level.setEnabled(true);
         nama_level.setEnabled(true);
        
         
         
        
         tambah.setEnabled(false);
         batal.setEnabled(true);
         hapus.setEnabled(true);
         ubah.setEnabled(true);
         tcari2.setText("");
         }else{
         JOptionPane.showMessageDialog(null,"Maaf Data Tidak Di Temukan");
         }
         stt.close();
         kon.close();
         
         }catch(Exception e){
             System.out.println("Error."+e);
         }
    }//GEN-LAST:event_ccari4ActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        String data[]=new String[5];
         Object[]options={"YA","TIDAK"};
        int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Menghapus Data?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        if(konfirmasi==JOptionPane.YES_OPTION){
            koneksi();
            try{
                    
                    Statement stt=kon.createStatement();
                    String SQL= "update level set nama_level ='"+nama_level.getText()+"'where id_level='"+id_level.getText()+"'";
                    stt.executeUpdate(SQL);
                    data[0]=id_level.getText();
                    data[1]=nama_level.getText();
                   
                    tblModel.removeRow(row);
                    tblModel.insertRow(row, data);
                    
                    stt.close();
                    kon.close();
                } catch(Exception exc){
                    System.err.printf(exc.getMessage());
                }
            normal();
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String il =id_level.getText();
        String nm = nama_level.getText();
        
        if((il.isEmpty())|(nm.isEmpty())){
        JOptionPane.showMessageDialog(null, "Masih ada nilai yang kosong silahkan di lengkapi");
        id_level.requestFocus();
    }else{
            Object[]options={"YA","TIDAK"};
            int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Menyimpan Data?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
            if(konfirmasi==JOptionPane.YES_OPTION){
                try{
                    koneksi();
                    Statement stt=kon.createStatement();
                    
                    String sql="insert into level values('"+id_level.getText()+"','"+nama_level.getText()+"')";
                    stt.executeUpdate(sql);
                    data[0]=id_level.getText();
                    data[1]=nama_level.getText();
                    
                    tblModel.insertRow(0,data);
                    normal();
                    stt.close();
                    kon.close();
                } catch(Exception exc){
                    System.err.printf(exc.getMessage());
                }
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         if(evt.getClickCount()==1){
        Tampil();
        id_level.setEnabled(true);
         nama_level.setEnabled(true);
        
         simpan.setEnabled(false);
         ubah.setEnabled(false);
         hapus.setEnabled(true);
         tambah.setEnabled(true);
          id_level.requestFocus();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    private void id_levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_levelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_levelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level().setVisible(true);
            }
        });
    }
    
    
        private void koneksi(){
    try{
    String hubung = "jdbc:mysql://localhost/db_hotel";
    Class.forName("com.mysql.jdbc.Driver");
    kon = DriverManager.getConnection(hubung,"root","");
    stt=kon.createStatement(rs.TYPE_SCROLL_SENSITIVE,rs.CONCUR_UPDATABLE);
    rs=stt.executeQuery("select*from level");
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    System.exit(0);
    }
    
    }
        
        
    int row=0;    
        public void Tampil(){
    row=jTable1.getSelectedRow();
    id_level.setText(tblModel.getValueAt(row, 0).toString());
    nama_level.setText(tblModel.getValueAt(row, 1).toString());
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton ccari4;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField id_level;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField nama_level;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tcari2;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
