/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotel_dawud;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.text.ParseException;
import javax.swing.JTable;
import java.io.File;
import java.sql.DriverManager;
import java.util.HashMap;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.swing.util.JRViewer;
//import net.sf.jasperreports.view.JasperView;
//import Report.CetakDataUser;
//import java.util.Locale;

/**
 *
 * @author CHACA
 */
public class user extends javax.swing.JFrame {
      public Connection kon;
    public Statement stt;
    public ResultSet rs;
    /**
     * Creates new form user
     */
    public user() {
        initComponents();
         normal();
        tabel1.setModel(tblModel);
        Tabel(tabel1,new int[]{55,110,210,110,110,110});
        setDefaultTable();
        tampil_combo();
    }
    
    
     private final javax.swing.table.DefaultTableModel tblModel = getDefaultTabelModel();
    
    private void Tabel(javax.swing.JTable tb, int lebar[]){
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int kolom=tb.getColumnCount();
        for(int i=0;i<kolom;i++){
            javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);
            tb.setRowHeight(17);
        }
    }
    
    private javax.swing.table.DefaultTableModel getDefaultTabelModel(){
        return new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"id_user","username","password","nama_user","nama_level"}){
                boolean[]canEdit=new boolean[]{
                    false,false,false,false};
        public boolean isCallEditable(int rowIndex,int coloumnIndex){
            return canEdit[coloumnIndex];
        }
        };
        }
    
    private void autokode(){
        String hubung = "jdbc:mysql://localhost:3306/db_hotel";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stmt = kon.createStatement();
            String SQL = "SELECT MAX(right(id_user,2)) AS no FROM user";
            ResultSet rs = stmt.executeQuery(SQL);
                while(rs.next())
                {
                    if(rs.first()==false)
                    {
                        kode_user.setText("0");
                    }
                    else
                    {
                        rs.last();
                        int auto_nis=rs.getInt(1)+1;
                        String no = String.valueOf(auto_nis);
                        int noLong = no.length();
                        for(int a=0;a<3-noLong;a++)
                    {
                        no = "0" + no;
                    }
                    kode_user.setText("0"+no);
                        } 
                }
                rs.close();
                stmt.close();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "ERROR:\n" + e.toString(),
                    "Kesalahan",JOptionPane.WARNING_MESSAGE);
        }
    }   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tcari = new javax.swing.JTextField();
        ccari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        kode_user = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nama_user = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tampil = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        tambah = new javax.swing.JButton();
        simpan1 = new javax.swing.JButton();
        batal1 = new javax.swing.JButton();
        ubah1 = new javax.swing.JButton();
        hapus1 = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        nama_level = new javax.swing.JComboBox();
        password = new javax.swing.JPasswordField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_dawud/123082-OQ5D5U-215.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        jLabel1.setText("User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 576, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukan Username");

        ccari.setBackground(new java.awt.Color(255, 102, 255));
        ccari.setForeground(new java.awt.Color(255, 255, 255));
        ccari.setText("Cari");
        ccari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ccari)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccari))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 67, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Kode_User");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 84, -1, -1));
        getContentPane().add(kode_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 85, 52, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 116, -1, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 117, 146, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Passwrod");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 148, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Nama_User");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 180, -1, -1));
        getContentPane().add(nama_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 181, 146, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Id_Level");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 212, -1, -1));

        tampil.setText("Show");
        tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilActionPerformed(evt);
            }
        });
        getContentPane().add(tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 148, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        simpan1.setText("Simpan");
        simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan1ActionPerformed(evt);
            }
        });

        batal1.setText("Batal");
        batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal1ActionPerformed(evt);
            }
        });

        ubah1.setText("Ubah");
        ubah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah1ActionPerformed(evt);
            }
        });

        hapus1.setText("Hapus");
        hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus1ActionPerformed(evt);
            }
        });

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(tambah)
                .addGap(18, 18, 18)
                .addComponent(simpan1)
                .addGap(18, 18, 18)
                .addComponent(batal1)
                .addGap(18, 18, 18)
                .addComponent(ubah1)
                .addGap(18, 18, 18)
                .addComponent(hapus1)
                .addGap(18, 18, 18)
                .addComponent(keluar)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(simpan1)
                    .addComponent(batal1)
                    .addComponent(ubah1)
                    .addComponent(hapus1)
                    .addComponent(keluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 263, -1, -1));

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_user", "username", "password", "nama_user", "nama_level"
            }
        ));
        tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 380, -1, 123));

        nama_level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        nama_level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_levelActionPerformed(evt);
            }
        });
        getContentPane().add(nama_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        
        String data[]=new String[5];
        // TODO add your handling code here:
    autokode();
    kode_user.setEnabled(false);
    username.requestFocus();
    nama_user.setEnabled(true);
    username.setEnabled(true);
    password.setEnabled(true);
    nama_level.setEnabled(true);
    tambah.setEnabled(false);
    simpan1.setEnabled(true);
    ubah1.setEnabled(false);
    batal1.setEnabled(true);
    hapus1.setEnabled(false);
    keluar.setEnabled(false);
    }//GEN-LAST:event_tambahActionPerformed

    private void simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan1ActionPerformed
        // TODO add your handling code here:
        
        String data[]=new String[5];
        String nm=username.getText();
        String ps=password.getText();
        String ns=nama_user.getText();
        if((nm.isEmpty())|(ps.isEmpty())|(ns.isEmpty())){
            JOptionPane.showMessageDialog(null,"Masih Ada Nilai Yang Kosong, Silahkan Dilengkapi");
            username.requestFocus();
        }
        else{
            Object[]options={"YA","TIDAK"};
            int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Menyimpan Data?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
            if(konfirmasi==JOptionPane.YES_OPTION){
                try{
                    koneksi();
                    Statement stt=kon.createStatement();
                    char[]pass=password.getPassword();
                    String passString=new String(pass);
                    String sql="insert into user values('"+kode_user.getText()+"','"+username.getText()+"','"+passString.toString()+"','"+nama_user.getText()+"','"+nama_level.getSelectedItem()+"')";
                    stt.executeUpdate(sql);
                    data[0]=kode_user.getText();
                    data[1]=username.getText();
                    data[2]=password.getText();
                    data[3]=nama_user.getText();
                    data[4]=nama_level.getSelectedItem().toString();
                    tblModel.insertRow(0,data);
                    normal();
                    stt.close();
                    kon.close();
                } catch(Exception exc){
                    System.err.printf(exc.getMessage());
                }
            }
        }
        kode_user.setText("");
    }//GEN-LAST:event_simpan1ActionPerformed

    private void hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus1ActionPerformed
        // TODO add your handling code here:
         Object[]options={"YA","TIDAK"};
        int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Menghapus Data?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        if(konfirmasi==JOptionPane.YES_OPTION){
            try{
                koneksi();
                Statement stt=kon.createStatement();
                String SQL="delete from user where id_user='"+kode_user.getText()+"'";
                stt.executeUpdate(SQL);
                tblModel.removeRow(row);
                normal();
                stt.close();
                kon.close();
            }catch(Exception exc){
                System.err.println(exc.getMessage());
            }
        }
    }//GEN-LAST:event_hapus1ActionPerformed

    private void batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal1ActionPerformed
        // TODO add your handling code here:
         normal();
        nama_user.setEnabled(false);
        nama_user.setText("");
        username.setEnabled(false);
        username.setText("");
        password.setEnabled(false);
        password.setText("");
        nama_level.setSelectedItem(false);
    }//GEN-LAST:event_batal1ActionPerformed

    private void ubah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah1ActionPerformed
        // TODO add your handling code here:
         String data[]=new String[5];
         Object[]options={"YA","TIDAK"};
        int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Menghapus Data?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        if(konfirmasi==JOptionPane.YES_OPTION){
            koneksi();
            try{
                    
                    Statement stt=kon.createStatement();
                    String SQL= "update user set password = '"+password.getText()+"',nama_user='"+nama_user.getText()+"',id_level='"+nama_level.getSelectedItem()+"',where id_user='"+kode_user.getText()+"'  ";
                    stt.executeUpdate(SQL);
                    data[0]=kode_user.getText();
                    data[1]=username.getText();
                    data[2]=password.getText();
                    data[3]=nama_user.getText();
                    data[4]=nama_level.getSelectedItem().toString();
                    tblModel.insertRow(0, data);
                    
                    stt.close();
                    kon.close();
                } catch(Exception exc){
                    System.err.printf(exc.getMessage());
                }
            normal();
        }
    }//GEN-LAST:event_ubah1ActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        String data[]=new String[5];
         Object[]options={"YA","TIDAK"};
        int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Menghapus Data?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        if(konfirmasi==JOptionPane.YES_OPTION){
         dispose();
                
            
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void ccariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccariActionPerformed
        // TODO add your handling code here:
         koneksi();
         try{
         String hubung = "jdbc:mysql://localhost:3306/db_hotel";
         Class.forName("com.mysql.jdbc.Driver").newInstance();
         Connection kon =DriverManager.getConnection(hubung, "root","");
         String cari = tcari.getText();
         String sql = "select * from user where username like '"+cari+"'";
         Statement stt = kon.createStatement();
         ResultSet res=stt.executeQuery(sql);
         if(res.next()){
         kode_user.setText(res.getString(1));
         username.setText(res.getString(2));
         password.setText(res.getString(3));
         nama_user.setText(res.getString(4));
         nama_level.setSelectedItem(res.getString(5));
         
         
         
         nama_user.setEnabled(true);
         username.setEnabled(true);
         password.setEnabled(true);
         nama_level.setEnabled(true);
         batal1.setEnabled(true);
         hapus1.setEnabled(true);
         ubah1.setEnabled(true);
         tcari.setText("");
         }else{
         JOptionPane.showMessageDialog(null,"Maaf Data Tidak Di Temukan");
         }
         stt.close();
         kon.close();
         
         }catch(Exception e){
             System.out.println("Error."+e);
         }
    }//GEN-LAST:event_ccariActionPerformed

    private void tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
        Tampil();
        kode_user.setEnabled(true);
         username.setEnabled(true);
         password.setEnabled(true);
         nama_user.setEnabled(true);
         nama_level.setSelectedItem(true);
         simpan1.setEnabled(false);
         hapus1.setEnabled(true);
         ubah1.setEnabled(true);
         tambah.setEnabled(true);
        }
    }//GEN-LAST:event_tabel1MouseClicked

    private void tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilActionPerformed
        // TODO add your handling code here:
        if(tampil.isSelected()==false){
        password.setEchoChar('*');
        }else{
        password.setEchoChar((char)0);
        }
    }//GEN-LAST:event_tampilActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    private void nama_levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_levelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_levelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }
    
    private void koneksi(){
    try{
    String hubung = "jdbc:mysql://localhost/db_hotel";
    Class.forName("com.mysql.jdbc.Driver");
    kon = DriverManager.getConnection(hubung,"root","");
    stt=kon.createStatement(rs.TYPE_SCROLL_SENSITIVE,rs.CONCUR_UPDATABLE);
    rs=stt.executeQuery("select*from user");
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    System.exit(0);
    }
    
    }
    
    
    public void normal(){
    nama_user.setText("");
    username.setText("");
    password.setText("");
    kode_user.setEnabled(false);
    nama_user.setEnabled(false);
    username.setEnabled(false);
    password.setEnabled(false);
    nama_level.setEnabled(false);
    tambah.setEnabled(true);
    simpan1.setEnabled(false);
    ubah1.setEnabled(false);
    hapus1.setEnabled(false);
    batal1.setEnabled(false);
    keluar.setEnabled(false);
    }
    
    int row =0;
    public void Tampil(){
    row=tabel1.getSelectedRow();
    kode_user.setText(tblModel.getValueAt(row, 0).toString());
    username.setText(tblModel.getValueAt(row, 1).toString());
    password.setText(tblModel.getValueAt(row, 2).toString());
    nama_user.setText(tblModel.getValueAt(row, 3).toString());
    nama_level.setSelectedItem(tblModel.getValueAt(row, 4).toString());
    
    
    nama_user.setEnabled(true);
    username.setEnabled(true);
    password.setEnabled(true);
    nama_level.setEnabled(true);
    }
    
     
    public void setDefaultTable(){
    String hubung = "jdbc:mysql://localhost:3306/db_hotel";
    String data[]=new String[5];
    try{
         Class.forName("com.mysql.jdbc.Driver").newInstance();
         Connection con =DriverManager.getConnection(hubung, "root","");
         Statement stt = con.createStatement();
         String sql = "Select*from user";
         ResultSet res=stt.executeQuery(sql);
         while(res.next()){
         data[0]=res.getString(1);
         data[1]=res.getString(2);
         data[2]=res.getString(3);
         data[3]=res.getString(4);
         data[4]=res.getString(5);
         tblModel.addRow(data);
         }
         res.close();
         stt.close();
         
    }catch(Exception exc){
        System.err.println(exc.getMessage());
    
    }
    }
    
    public void tampil_combo(){
    String hubung = "jdbc:mysql://localhost/db_hotel";
    try{
         Class.forName("com.mysql.jdbc.Driver").newInstance();
         Connection con =DriverManager.getConnection(hubung, "root","");
         Statement stt = con.createStatement();
         String sql ="Select id_level from level order by id_level asc";
          ResultSet res=stt.executeQuery(sql);
          while(res.next()){
          Object[] ob=new Object[1];
          ob[0]=res.getString(1);
          
          
          nama_level.addItem(ob[0]);
          }
            res.close();
    stt.close();
    con.close();
    } catch(Exception exc){
        System.err.println(exc.getMessage());
}
    }
  
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal1;
    private javax.swing.JButton ccari;
    private javax.swing.JButton hapus1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kode_user;
    private javax.swing.JComboBox nama_level;
    private javax.swing.JTextField nama_user;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton simpan1;
    private javax.swing.JTable tabel1;
    private javax.swing.JButton tambah;
    private javax.swing.JCheckBox tampil;
    private javax.swing.JTextField tcari;
    private javax.swing.JButton ubah1;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

   

   
}
